#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Bash
ln -sf $DOTFILES/bash/bashrc $HOME/.bashrc
ln -sf $DOTFILES/bash/alias $HOME/.alias

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

# Kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
