#!/usr/bin/env bash

# Require non-root sudo user
if [[ $EUID -eq 0 ]]; then
  echo "Please run this command as your normal user, not root (or sudo.)"
  exit 1
fi

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

safe_link() {
  if [ "$#" -ne 2 ]; then
    echo "Usage: safe_link <source_dir> <destination_link>"
    return 1
  fi

  local src="$1"
  local dest="$2"

  # If file exists, or it's a link
  if [ -e "$dest" ] || [ -L "$dest" ]; then
    # If not a link, or not pointing to target, backup
    if [ ! -L "$dest" ] || [ ! "$(readlink "$dest")" = "$src" ]; then
      # Back up the existing file/folder using a timestamp
      local backup_name="${dest}.bk_$(date +%Y%m%d_%H%M%S)"
      mv "$dest" "$backup_name"

      ln -s "$src" "$dest"
    fi
  else
    ln -s "$src" "$dest"
  fi
}

# Bash
safe_link $DOTFILES/bash/.bashrc $HOME/.bashrc
safe_link $DOTFILES/bash/.alias $HOME/.alias
safe_link $DOTFILES/bash/.prompt $HOME/.prompt
safe_link $DOTFILES/bash/.inputrc $HOME/.inputrc

# Git
safe_link $DOTFILES/git/.gitconfig $HOME/.gitconfig

# Kitty
safe_link $DOTFILES/kitty $HOME/.config/kitty

# Tmux
safe_link $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# SSH key
SSH_KEY="$HOME/.ssh/id_ed25519"
if [[ ! -f "$SSH_KEY" ]]; then
  read -rp "SSH key '$SSH_KEY' not found. Generate one now? [y/N]: " PROMPT </dev/tty
  if [[ "$PROMPT" =~ ^[yY]$ ]]; then
    mkdir -p $(dirname "$SSH_KEY")
    chmod 700 "$(dirname "$SSH_KEY")"
    ssh-keygen -t ed25519 -f "$SSH_KEY"
  fi
fi

# SSH agent
mkdir -p $HOME/.config/systemd/user
ln -sf $DOTFILES/systemd/ssh-agent.service $HOME/.config/systemd/user/ssh-agent.service
systemctl --user daemon-reload
systemctl --user enable --quiet --now ssh-agent.service

# Custom functions
rm -rf $HOME/.local/bin
safe_link $DOTFILES/bin $HOME/.local/bin

# Hyprland
rm -rf $HOME/.config/hypr
safe_link $DOTFILES/hyprland $HOME/.config/hypr

# Prusa Slicer
rm -r $HOME/.config/PrusaSlicer/filament
rm -r $HOME/.config/PrusaSlicer/print
safe_link $DOTFILES/prusa-slicer/filament $HOME/.config/PrusaSlicer/filament
safe_link $DOTFILES/prusa-slicer/print $HOME/.config/PrusaSlicer/print

# Google Drive links
for dir in Desktop Documents Music Videos; do
  safe_link "$HOME/GoogleDrive/$dir" "$HOME/$dir"
done

# Refresh config
source $HOME/.bashrc
